
name: Stage

on:
  push:
    branches: stage

jobs:
  build_and_deploy:
    name: Deploy to firebase hosting
    environment: stage
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
      - name: use nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install -g firebase-tools
      - run: npm install
      - run: CI=false npm run build
      - run: |
          echo ${{ steps.auth.outputs.project_id }}
          firebase use --add ${{ steps.auth.outputs.project_id }}
          firebase deploy --only hosting # --token $FIREBASE_TOKEN

  
env:
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
  REACT_APP_BUILD_ENV: dev
