on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
      - develop
  pull_request:
      types: [ opened, synchronize, reopened ]
name: Unit Tests
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install dependencies
      run:  npm install
    - name: Run Tests
      run:  npm run test
    - name: Fix code coverage paths
      working-directory: ./coverage
      run: |
        sed -i 's/\/home\/runner\/work\/admin-client\/admin-client\//\/github\/workspace\//g' lcov.info
        sed -i 's/\/home\/runner\/work\/admin-client\/admin-client\//\/github\/workspace\//g' ../test-report.xml
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}